security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            custom_authenticators:
                - App\Security\LoginFormAuthenticator 
            provider: app_user_provider
            entry_point: form_login

            # Configuration du formulaire de login
            form_login:
                login_path: app_login       # route de la page de connexion
                check_path: app_login       # route pour soumettre les identifiants
                enable_csrf: true           # activer la protection CSRF pour le login
            logout:
                path: app_logout
                target: app_login           # route de redirection après déconnexion
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800            # durée de vie du cookie (7 jours)
                path: /


    access_control:
        #- { path: ^/connexion, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }
