security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            # Ajout de custom_authenticators
            custom_authenticators:
                - App\Security\LoginFormAuthenticator
            provider: app_user_provider
            # Définition explicite du entry_point
            entry_point: App\Security\LoginFormAuthenticator  # C'est ici que l'on définit l'entrée (point d'entrée)
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: films_liste
                username_parameter: email
                password_parameter: password
                csrf_token_id: authenticate
                enable_csrf: true
                remember_me: true  # Utiliser un booléen pour activer la fonctionnalité "remember me"
            logout:
                path: app_logout
                target: app_login

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /

    access_control:
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }
